@AgentDo.Web_HostAddress = http://localhost:5177

POST {{AgentDo.Web_HostAddress}}/generate
Content-Type: application/json

{
  "query": "Hello. What can you do?"
}

###

GET {{AgentDo.Web_HostAddress}}/history


###

GET {{AgentDo.Web_HostAddress}}/tools
